"use client";

import { ArrowRight, Bookmark, BookmarkCheck, Clock3, Download, History, Settings } from "lucide-react";
import type { Dispatch, ElementType, ReactNode, SetStateAction } from "react";
import { browserRoutes } from "../../data/navigation";
import { nolineConfig } from "../../config/noline.config";

export function HistoryPage({ items, onOpen }: { items: string[]; onOpen: (url: string) => void }) {
  return <UtilityShell icon={History} kicker="BROWSER" title="History" description="Local browsing history until the game identity layer exists.">{items.length ? items.map((url, i) => <button className="utility-row" key={url+i} onClick={() => onOpen(url)}><Clock3 size={15}/><span><strong>{url}</strong><small>Recent NOLINE visit</small></span><ArrowRight size={13}/></button>) : <Empty title="Nothing here yet." body="Visit NOLINE services and they will appear here."/>}</UtilityShell>;
}
export function BookmarksPage({ items, onOpen }: { items: string[]; onOpen: (id: string) => void }) {
  return <UtilityShell icon={Bookmark} kicker="BROWSER" title="Bookmarks" description="Saved catalog items. They stay local until profile sync is connected.">{items.length ? items.map((id) => <button className="utility-row" key={id} onClick={() => onOpen(id)}><BookmarkCheck size={15}/><span><strong>{id}</strong><small>{browserRoutes.showroom}</small></span><ArrowRight size={13}/></button>) : <Empty title="No bookmarks." body="Bookmark a vehicle from its inspection page."/>}</UtilityShell>;
}
export function DownloadsPage() { return <UtilityShell icon={Download} kicker="BROWSER" title="Downloads" description="Native surface for future receipts, documents and game-generated files."><Empty title="Your downloads are empty." body="Receipts and exported files can appear here later."/></UtilityShell>; }
export function SettingsPage({ settings, setSettings }: { settings: { motion: boolean; glass: boolean; compact: boolean }; setSettings: Dispatch<SetStateAction<{ motion: boolean; glass: boolean; compact: boolean }>> }) {
  return <UtilityShell icon={Settings} kicker="BROWSER" title="Settings" description="Presentation preferences are local today and can become profile-backed later."><div className="settings-card"><Setting title="Motion" detail="Smooth transitions and purchase feedback." enabled={settings.motion} onClick={() => setSettings((s) => ({...s,motion:!s.motion}))}/><Setting title="Liquid glass" detail="Translucent browser chrome and layered panels." enabled={settings.glass} onClick={() => setSettings((s) => ({...s,glass:!s.glass}))}/><Setting title="Compact mode" detail="Tighter spacing for smaller displays." enabled={settings.compact} onClick={() => setSettings((s) => ({...s,compact:!s.compact}))}/><div className="settings-note">NOLINE intentionally has no account system yet. Core settings mirror <b>{nolineConfig.integration.bridgeKey}</b> readiness.</div></div></UtilityShell>;
}
export function ConfigPage() {
  return <UtilityShell icon={Settings} kicker="CONFIGURATION" title="NOLINE Configuration" description="Central configuration is isolated from catalog and presentation code so the game can change behavior without touching components."><div className="config-grid"><ConfigRow name="Command trigger" value={nolineConfig.brand.commandTrigger}/><ConfigRow name="Default route" value={nolineConfig.browser.defaultRoute}/><ConfigRow name="Currency" value={nolineConfig.commerce.currency}/><ConfigRow name="Account requirement" value={nolineConfig.commerce.accountRequired ? "Required" : "Disabled"}/><ConfigRow name="Purchase boundary" value={nolineConfig.commerce.purchaseBoundary}/><ConfigRow name="Game bridge" value={nolineConfig.integration.bridgeKey}/><ConfigRow name="Featured vehicle" value={nolineConfig.catalog.featuredVehicleId}/><ConfigRow name="Sale pricing" value={nolineConfig.catalog.showSalePrices ? "Visible" : "Hidden"}/><ConfigRow name="Special stock" value={nolineConfig.catalog.showSpecialVehicles ? "Visible" : "Hidden"}/></div></UtilityShell>;
}
function ConfigRow({ name, value }: { name: string; value: string }) { return <div className="config-row"><span>{name}</span><strong>{value}</strong></div>; }
function Setting({ title, detail, enabled, onClick }: { title: string; detail: string; enabled: boolean; onClick: () => void }) { return <div className="setting"><div><strong>{title}</strong><p>{detail}</p></div><button className={`switch ${enabled ? "on" : ""}`} onClick={onClick}><span/></button></div>; }
function UtilityShell({ icon: Icon, kicker, title, description, children }: { icon: ElementType; kicker: string; title: string; description: string; children: ReactNode }) { return <div className="page"><div className="page-head"><span className="kicker">{kicker}</span><h1>{title}</h1><p>{description}</p></div><div className="utility-card"><div className="utility-icon"><Icon size={18}/></div>{children}</div></div>; }
function Empty({ title, body }: { title: string; body: string }) { return <div className="empty"><span><Download size={20}/></span><h3>{title}</h3><p>{body}</p></div>; }
